[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/xanzy/go-gitlab"
  version = "~0.9.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~v1.1.0"